theme: jekyll-theme-minimal
title: "Kade-Engine"
description: "Kade-Engine Is A Modification for Friday Night Funkin' inculding reworked inputs, ratings, and brand new options!
show_downloads: "true"
logo: "https://github.com/KadeDev/Kade-Engine/raw/master/KadeEngineLogo.png"
